// Code generated by "stringer -linecomment -type GGUFFileType -output zz_generated.gguffiletype.stringer.go -trimprefix GGUFFileType"; DO NOT EDIT.

package gguf_parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GGUFFileTypeAllF32-0]
	_ = x[GGUFFileTypeMostlyF16-1]
	_ = x[GGUFFileTypeMostlyQ4_0-2]
	_ = x[GGUFFileTypeMostlyQ4_1-3]
	_ = x[GGUFFileTypeMostlyQ4_1_F16-4]
	_ = x[GGUFFileTypeMostlyQ4_2-5]
	_ = x[GGUFFileTypeMostlyQ4_3-6]
	_ = x[GGUFFileTypeMostlyQ8_0-7]
	_ = x[GGUFFileTypeMostlyQ5_0-8]
	_ = x[GGUFFileTypeMostlyQ5_1-9]
	_ = x[GGUFFileTypeMostlyQ2_K-10]
	_ = x[GGUFFileTypeMostlyQ3_K-11]
	_ = x[GGUFFileTypeMostlyQ4_K-12]
	_ = x[GGUFFileTypeMostlyQ5_K-13]
	_ = x[GGUFFileTypeMostlyQ6_K-14]
	_ = x[GGUFFileTypeMostlyIQ2_XXS-15]
	_ = x[GGUFFileTypeMostlyIQ2_XS-16]
	_ = x[GGUFFileTypeMostlyIQ3_XXS-17]
	_ = x[GGUFFileTypeMostlyIQ1_S-18]
	_ = x[GGUFFileTypeMostlyIQ4_NL-19]
	_ = x[GGUFFileTypeMostlyIQ3_S-20]
	_ = x[GGUFFileTypeMostlyIQ2_S-21]
	_ = x[GGUFFileTypeMostlyIQ4_XS-22]
	_ = x[GGUFFileTypeMostlyIQ1_M-23]
	_ = x[GGUFFileTypeMostlyBF16-24]
	_ = x[GGUFFileTypeMostlyQ4_0_4_4-25]
	_ = x[GGUFFileTypeMostlyQ4_0_4_8-26]
	_ = x[GGUFFileTypeMostlyQ4_0_8_8-27]
	_ = x[GGUFFileTypeMostlyTQ1_0-28]
	_ = x[GGUFFileTypeMostlyTQ2_0-29]
	_ = x[GGUFFileTypeMostlyIQ4_NL_4_4-30]
	_ = x[GGUFFileTypeMostlyIQ4_NL_4_8-31]
	_ = x[GGUFFileTypeMostlyIQ4_NL_8_8-32]
	_ = x[_GGUFFileTypeCount-33]
}

const _GGUFFileType_name = "F32F16Q4_0Q4_1Q4_1_F16Q4_2Q4_3Q8_0Q5_0Q5_1Q2_KQ3_K/Q3_K_SQ4_K/Q3_K_MQ5_K/Q3_K_LQ6_K/Q4_K_SIQ2_XXS/Q4_K_MIQ2_XS/Q5_K_SIQ3_XXS/Q5_K_MIQ1_S/Q6_KIQ4_NLIQ3_SIQ2_SIQ4_XSIQ1_MBF16Q4_0_4x4Q4_0_4x8Q4_0_8x8TQ1_0TQ2_0IQ4_NL_4x4IQ4_NL_4x8IQ4_NL_8x8Unknown"

var _GGUFFileType_index = [...]uint8{0, 3, 6, 10, 14, 22, 26, 30, 34, 38, 42, 46, 57, 68, 79, 90, 104, 117, 131, 141, 147, 152, 157, 163, 168, 172, 180, 188, 196, 201, 206, 216, 226, 236, 243}

func (i GGUFFileType) String() string {
	if i >= GGUFFileType(len(_GGUFFileType_index)-1) {
		return "GGUFFileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GGUFFileType_name[_GGUFFileType_index[i]:_GGUFFileType_index[i+1]]
}
